### ISSUE TITLE
Some Notes

### ISSUE THREAD

**Issue by RecklessGlue540** [Tomasak/Console-Visuals#1]
I forgot to mention earlier, but on console, the annihilator miniguns fire at a slower rate than on PC. This is caused by a difference in it's weaponinfo.xml lines. I reckon it could be included under Console Weapon Animations, so here's the file: https://www.mediafire.com/file/5j11y36a5979dss/weaponinfo.xml/file

Furthermore, the ConsoleVehicleAnimations archive, I feel like it should be placed in update/ConsoleVisuals, rather than update/ConsoleVisuals/IV, since shouldn't it be loaded in all episodes?

And one question:
I see that [Console Peds by Attramet](https://gtaforums.com/topic/989680-attramets-workshop/#comments) hasn't been updated yet. Is this intentional for the moment?

**Comment by Tomasak** [comment]
done, thanks for info
