### ISSUE TITLE
[Suggestion] Make Console Loading Screens go in order, just like in console

### ISSUE THREAD

**Issue by DAMNED117** [Tomasak/Console-Visuals#3]
The IV loading screens on console always go in the same order every time. First is Niko behind crates, then the lollipop girl, etc. But with this mod, the order is always random. Here's an example of what the order should be for this mod to match the consoles (order is from left to right): https://gta.fandom.com/wiki/Entry_Screen#GTA_IV_Console

The only mod that I've seen so far that did the order right is this mod by nkjellman: https://www.gtagarage.com/mods/show.php?id=16214

Unfortunately, the mod linked above has one issue, and that is the loading screens are not upscaled/high quality like Console Visuals.

Your version of the console loading screens is perfect, only thing it's missing is the order that the PS3 & Xbox 360 always stick to.

**Comment by RecklessGlue540** [comment]
Loading is so fast with FusionFix, you barely get to see the first loading screen. 
Making this change of making every screen play in order would be rather boring, as the first screen would always play out making the rest actually useless to keep if you ask me. It's better the way it currently is imo. It's randomised, just like EFLC's, and just like the ones during mid game load for all episodes.

What if the specific order was an oversight even? Since I believe it doesn't really even make sense to make them go by a specific order.

**Comment by DAMNED117** [comment]
I get your perspective and where you're coming from, but the only reason I want it to go in order is that I don't wanna get randomly flashed sometimes by the prostitute loading screen lol, I'd rather look at Niko behind the crates instead of taking a gamble on what will the first loading screen be every time. I don't have the same argument with EFLC since they start with their titles first before showing the loading screens, and at least on my end with FusionFix as you said, I don't even get to see the first loading screen before the game's finished loading.

And besides, correct me if I'm wrong on this since it's been a while since I played this game on console, but both TBoGT & TLAD's loading screens also have an order to stick to; at least from what I've seen on YouTube of multiple EFLC console loading screen videos going in the same order.

But you're right. On second thought, I don't think it matters as FusionFix almost skips the loading screens entirely... unless there's a mod to purposely make the loading screens longer (at least for IV) just so I can enjoy the loading screen's theme which I wish for 'till this day lol.

**Comment by UserGit-2021** [comment]
> I get your perspective and where you're coming from, but the only reason I want it to go in order is that I don't wanna get randomly flashed sometimes by the prostitute loading screen lol, I'd rather look at Niko behind the crates instead of taking a gamble on what will the first loading screen be every time. I don't have the same argument with EFLC since they start with their titles first before showing the loading screens, and at least on my end with FusionFix as you said, I don't even get to see the first loading screen before the game's finished loading.
> 
> And besides, correct me if I'm wrong on this since it's been a while since I played this game on console, but both TBoGT & TLAD's loading screens also have an order to stick to; at least from what I've seen on YouTube of multiple EFLC console loading screen videos going in the same order.
> 
> But you're right. On second thought, I don't think it matters as FusionFix almost skips the loading screens entirely... unless there's a mod to purposely make the loading screens longer (at least for IV) just so I can enjoy the loading screen's theme which I wish for 'till this day lol.

Unfortunately, this suggestion is useless, because the game is loading very quickly. All answered by user RecklessGlue540. If the loading was in strict order, then I would not have seen the rest of the loading screens.
Better to close this topic.

**Comment by DAMNED117** [comment]
> Unfortunately, this suggestion is useless, because the game is loading very quickly. All answered by user RecklessGlue540. If the loading was in strict order, then I would not have seen the rest of the loading screens. Better to close this topic.

Damn I forgot I left this issue open xD, my bad. I've finally convinced myself that this suggestion is actually useless. Thx for the reminder ;)
